version: "3.7"

services:
    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1
            #MYSQL_HOST: 127.0.0.1
        networks:
            - clarusnet
    flask-app:
        container_name: flask-app
        image: aydintokuslu/bookstore-api:1.0
        restart: always
        depends_on:
            - mysql-db
        ports:
            - "80:80"
        networks:
            - clarusnet

networks:
    clarusnet:
        driver: bridge